version: '3'
services:
  frontend:
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    volumes:
      - ./backend:/app/backend
      - ./dist:/app/dist
